name: wisp
channels:
  - conda-forge
  - fastai
dependencies:
  - python==3.8.10
  - numpy==1.25.2
  - astropy==5.2.1
  - matplotlib==3.7.2
  - pyyaml==6.0.1
  - pandas==2.1.0
  - tqdm==4.66.1
  - Pillow==10.0.0
  - scipy==1.5.2
  - scikit-learn==1.3.0
  - pytorch==1.13.0
  - nvidia-ml-py3==7.352.0
  - scikit-image==0.19.3
  - requests==2.31.0
  - configargparse==1.7
  - tensorboard==2.13.0
