parent: base_narval.yaml

global:
    use_tqdm: False
    exp_name: 'vipers-spectra-ssim'
    # log_fname: ''

    tasks: ['codebook_pretrain'] #,'recon_spectra']
    #tasks: ['codebook_pretrain_infer','plot_global_lambdawise_spectra_loss'] #'plot_spectra_latents_pca'

optimizer:
    optimizer_type: 'adam'

    b1: 0.5
    b2: 0.999
    lr: 1e-4
    spectra_latents_lr: 1e-3
    codebook_pretrain_lr: 1e-3
    weight_decay: 1e-5

    sgd_momentum: 0.9

embedder:
    encode_wave: True
    wave_encode_method: positional_encoding
    wave_embed_dim: 16

pretrain:
    pretrain_batch_size: 20000

    pretrain_use_all_wave: False
    pretrain_num_wave_samples: 100
    pretrain_wave_sample_method: 'uniform_dense'

    apply_gt_redshift: True
    calculate_binwise_spectra_loss: False # brute force, each bin has its own spectra

    # if brute force, we have three choices
    regularize_binwise_spectra_latents: False      # conflicts each other
    optimize_latents_for_each_redshift_bin: False  #
    # optimize_one_latent_for_all_redshift_bins:  # hidden, True if the other two False

    calculate_spectra_loss_based_on_optimal_bin: False # only if we use single latent
    calculate_spectra_loss_based_on_top_n_bins: True # only if we use single latent
    num_bins_to_calculate_spectra_loss: 5

    spectra_latent_dim: 16

    load_pretrained_spectra_latents: False
    load_pretrained_spectra_latents_to_gt_bin_only: False
    optimize_gt_bin_only: False
    dont_optimize_gt_bin: False

    pretrain_log_dir: ''
    pretrained_model_name: 'model-ep20000-bch0.pth'

    regularize_spectra_latents: True
    spectra_latents_regu_beta: 32

decoder:
    decoder_activation_type: relu #gaussian
    decoder_batch_norm: False
    decoder_num_hidden_layers: 5
    decoder_hidden_dim: 512
    decoder_skip_layers: []

    decoder_gaussian_sigma: .1

    decoder_activate_before_latents_skip: False
    decoder_latents_skip_all_layers: True
    decoder_latents_skip_method: 'add'
    decoder_latents_skip_add_conversion_method: 'multi_conversion'

    siren_seed: 0
    siren_first_w0: 24
    siren_hidden_w0: 6
    siren_coords_scaler: 1
    siren_last_linear: True

trainer:
    num_epochs: 5000
    batch_size: 5500
    log_cli_every: 500
    plot_grad_every: -1
    save_data_every: -1
    save_model_every: 500

    plot_l2_loss: True

    resume_train: False
    resume_log_dir: ''
    resume_model_fname: 'model-ep2000-bch0.pth'

    spectra_loss_cho: ssim1d
    spectra_loss_reduction: mean
    spectra_ssim_loss_filter_size: 9
    spectra_ssim_loss_filter_sigma: 5

infer:
    infer_last_model_only: True

    # infer_log_dir: ''
    infer_selected: False
    pretrain_num_infer_upper_bound: 140
    spectra_inferrence_id_fname: '' #'/redshift/model-0_redshift_outlier_ids.npy'
    infer_outlier_only: False

    pretrain_infer_batch_size: 1
    pretrain_infer_use_all_wave: True
    pretrain_infer_num_wave: 200
    pretrain_infer_wave_sample_method: 'uniform_dense'

    plot_clipped_spectrum: True
    plot_spectrum_with_loss: False
    plot_spectrum_with_ivar: False
    plot_spectrum_with_lines: False
    plot_spectrum_with_recon: True
    plot_spectrum_color_based_on_loss: False
    plot_spectrum_under_gt_bin: False
    plot_spectrum_under_optimal_wrong_bin: False
    plot_global_lambdawise_spectra_loss_with_ivar: False
    plot_global_lambdawise_spectra_loss_with_lines: False
    emitted_wave_overlap_discretization_val: 1e-1

    num_spectrum_per_fig: 35
    num_spectrum_per_row: 7

    sanity_check_plot_same_pca_dim_as_pretrain: True
    pretrain_pca_dim_fname: '' #/latents/2-dim/selected_axes.npy'
    spectra_latents_plot_pca_dim: 2

spectra_data:
    require_only_basic_spectra: True

    spectra_cho: v1
    spectra_process_patch_info: False
    spectra_data_sources: [vipers_w1,vipers_w4]
    random_permute_source_spectra: True

    min_num_valid_samples: 100
    spectra_upsample_scale: 10
    convolve_spectra: True
    process_ivar: True
    spectra_smooth_sigma: 15

    num_gt_spectra_upper_bound: 200000
    num_supervision_spectra_upper_bound: 200000

    filter_redshift: False
    filter_redshift_lo: 0.02
    filter_redshift_hi: -1

ablation:
    perform_ablation: False
    ablat_id: 0
    ablat_params: ["decoder_num_hidden_layers","regularize_spectra_latents"]
    ablat_vals: [[3,5],[True,False]]
    ablat_num_vals: [2,2]

    #ablat_hardcode_params: ["pretrain_log_dir"]
    #ablat_hardcode_vals: [["20240222-015410_1600-spectra-skip-same-dim_decoder_batch_norm_True","20240222-165434_1600-spectra-skip-same-dim_decoder_batch_norm_False"]]

    #"20240222-165402_1600-spectra-skip_decoder_batch_norm_True","20240222-165402_1600-spectra-skip_decoder_batch_norm_False"]]