parent: base_cc.yaml

global:
    use_tqdm: False
    exp_name: vdz-spectra-baseline
    log_fname: baseline

    tasks: [train, redshift_pretrain]
    tasks: [infer, redshift_pretrain_infer, save_redshift, plot_redshift_est_residuals, plot_redshift_est_stats]
    # tasks: ['infer','redshift_test_infer','save_redshift','plot_redshift_est_residuals','plot_redshift_est_stats']

optimizer:
    optimizer_type: adam

    b1: 0.5
    b2: 0.999
    lr: 1e-4
    baseline_lr: 1e-5
    classifier_lr: 1e-3
    spectra_latents_lr: 1e-3
    spectra_pretrain_lr: 1e-3
    weight_decay: 1e-5

    sgd_momentum: 0.9

pretrain:
    pretrain_batch_size: 100000
    pretrain_use_all_wave: True

    model_redshift: True
    redshift_model_method: classification #regression
    redshift_classification_strategy: binary

decoder:
    baseline_decoder_input_dim: 280
    baseline_decoder_num_hidden_layers: 3
    baseline_decoder_hidden_dim: 512

    baseline_decoder_batch_norm: True
    baseline_decoder_activate_before_skip: False
    baseline_decoder_skip_all_layers: False
    baseline_decoder_skip_method: add
    baseline_decoder_skip_add_conversion_method: multi_conversion

trainer:
    num_epochs: 20000
    batch_size: 5500
    log_cli_every: 2000
    plot_grad_every: -1
    save_data_every: -1
    save_model_every: 2000

    resume_train: False
    resume_log_dir: ''
    resume_model_fname: model-ep20000-bch0.pth

infer:
    infer_last_model_only: True

    # infer_log_dir: ''
    infer_selected: False
    pretrain_num_infer_upper_bound: 140
    spectra_inferrence_id_fname: '' #'/redshift/model-0_redshift_outlier_ids.npy'
    infer_outlier_only: False

    pretrain_infer_batch_size: 10
    pretrain_infer_use_all_wave: True

    plot_clipped_spectrum: True
    plot_spectrum_with_loss: False
    plot_spectrum_with_ivar: False
    plot_spectrum_with_lines: False
    plot_spectrum_with_recon: True
    plot_spectrum_color_based_on_loss: False
    plot_spectrum_under_gt_bin: False
    plot_spectrum_under_optimal_wrong_bin: False
    plot_global_lambdawise_spectra_loss_with_ivar: False
    plot_global_lambdawise_spectra_loss_with_lines: False
    emitted_wave_overlap_discretization_val: 1e-1

    num_spectrum_per_fig: 35
    num_spectrum_per_row: 7

    spectra_latents_plot_pca_dim: 2

dataset:
    calculate_wave_range_based_on_trans: False
    calculate_wave_range_based_on_spectra: True
    wave_range_fname: wave_range_spectra_6k_to_8k.npy

spectra_data:
    require_only_basic_spectra: True

    spectra_cho: v1
    spectra_process_patch_info: False
    spectra_data_sources: [deimos,zcosmos,vipers_w1,vipers_w4]
    random_permute_source_spectra: True

    spectra_supervision_wave_lo: 6000
    spectra_supervision_wave_hi: 8000

    min_num_valid_samples: 100
    spectra_upsample_scale: 10
    convolve_spectra: True
    process_ivar: True
    spectra_smooth_sigma: 15

    redshift_regress_spectra_sample_method: uniform_dense

    generalization_max_num_spectra: 10000
    num_gt_spectra_upper_bound: 200000
    num_supervision_spectra_upper_bound: 200000

    filter_redshift: False
    filter_redshift_lo: 0.02
    filter_redshift_hi: -1

ablation:
    perform_ablation: False
    ablat_id: 0
    ablat_params: ["spectra_latents_regu_beta","spectra_latent_dim"]
    ablat_vals: [[4,8,16],[16,32,64]]
    ablat_num_vals: [3,3]

    # ablat_hardcode_params: [infer_log_dir]
    # ablat_hardcode_vals: [[30-20240523-231831_pretrain_3_layers_spectra_latents_regu_beta_4_spectra_latent_dim_16,31-20240523-231839_pretrain_3_layers_spectra_latents_regu_beta_4_spectra_latent_dim_32,32-20240523-231832_pretrain_3_layers_spectra_latents_regu_beta_4_spectra_latent_dim_64]]