parent: base_narval.yaml

global:
    use_tqdm: False
    exp_name: 'autodecoder-3200-spectra-no-skip'
    log_fname: 'sc'

    tasks: ['codebook_pretrain']
    #tasks: ['codebook_pretrain_infer','plot_spectra_latents_pca'] #'save_redshift','plot_redshift_residual','plot_redshift_logits']
    tasks: ['redshift_pretrain']
    tasks: ['redshift_pretrain_infer','save_redshift'] #'plot_redshift_logits','plot_redshift_residual'] #'plot_spectra_latents_pca'

ablation:
    perform_ablation: True
    ablat_id: 0
    ablat_params: ["spectra_latent_dim","decoder_num_hidden_layers","decoder_hidden_dim"]
    ablat_vals: [[8,16,32],[3,5],[128,256,512]]
    ablat_num_vals: [3,2,3]

    #ablat_hardcode_params: ["pretrain_log_dir"]
    #ablat_hardcode_vals: [['20240225-001406_spectra_latent_dim_8_decoder_num_hidden_layers_3_decoder_hidden_dim_128','20240225-001406_spectra_latent_dim_8_decoder_num_hidden_layers_3_decoder_hidden_dim_256','20240225-001406_spectra_latent_dim_8_decoder_num_hidden_layers_3_decoder_hidden_dim_512','20240225-001419_spectra_latent_dim_8_decoder_num_hidden_layers_5_decoder_hidden_dim_128','20240225-001541_spectra_latent_dim_8_decoder_num_hidden_layers_5_decoder_hidden_dim_256','20240225-001542_spectra_latent_dim_8_decoder_num_hidden_layers_5_decoder_hidden_dim_512','20240225-001545_spectra_latent_dim_16_decoder_num_hidden_layers_3_decoder_hidden_dim_128','20240225-001554_spectra_latent_dim_16_decoder_num_hidden_layers_3_decoder_hidden_dim_256','20240225-001604_spectra_latent_dim_16_decoder_num_hidden_layers_3_decoder_hidden_dim_512','20240225-001634_spectra_latent_dim_16_decoder_num_hidden_layers_5_decoder_hidden_dim_128','20240225-001649_spectra_latent_dim_16_decoder_num_hidden_layers_5_decoder_hidden_dim_256','20240225-001725_spectra_latent_dim_16_decoder_num_hidden_layers_5_decoder_hidden_dim_512','20240225-001731_spectra_latent_dim_32_decoder_num_hidden_layers_3_decoder_hidden_dim_128','20240225-001841_spectra_latent_dim_32_decoder_num_hidden_layers_3_decoder_hidden_dim_256','20240225-001758_spectra_latent_dim_32_decoder_num_hidden_layers_3_decoder_hidden_dim_512','20240225-001809_spectra_latent_dim_32_decoder_num_hidden_layers_5_decoder_hidden_dim_128','20240225-001829_spectra_latent_dim_32_decoder_num_hidden_layers_5_decoder_hidden_dim_256','20240225-001829_spectra_latent_dim_32_decoder_num_hidden_layers_5_decoder_hidden_dim_512']]

    ablat_hardcode_params: ['infer_log_dir']
    ablat_hardcode_vals: [['20240226-012848_sc_spectra_latent_dim_8_decoder_num_hidden_layers_3_decoder_hidden_dim_128','20240226-012848_sc_spectra_latent_dim_8_decoder_num_hidden_layers_3_decoder_hidden_dim_256','20240226-022859_sc_spectra_latent_dim_8_decoder_num_hidden_layers_3_decoder_hidden_dim_512','20240226-015346_sc_spectra_latent_dim_8_decoder_num_hidden_layers_5_decoder_hidden_dim_128','20240226-022407_sc_spectra_latent_dim_8_decoder_num_hidden_layers_5_decoder_hidden_dim_256','20240226-023403_sc_spectra_latent_dim_8_decoder_num_hidden_layers_5_decoder_hidden_dim_512','20240226-015346_sc_spectra_latent_dim_16_decoder_num_hidden_layers_3_decoder_hidden_dim_128','20240226-015346_sc_spectra_latent_dim_16_decoder_num_hidden_layers_3_decoder_hidden_dim_256','20240226-022859_sc_spectra_latent_dim_16_decoder_num_hidden_layers_3_decoder_hidden_dim_512','20240226-015356_sc_spectra_latent_dim_16_decoder_num_hidden_layers_5_decoder_hidden_dim_128','20240226-022407_sc_spectra_latent_dim_16_decoder_num_hidden_layers_5_decoder_hidden_dim_256','20240226-023936_sc_spectra_latent_dim_16_decoder_num_hidden_layers_5_decoder_hidden_dim_512','20240226-015829_sc_spectra_latent_dim_32_decoder_num_hidden_layers_3_decoder_hidden_dim_128','20240226-015829_sc_spectra_latent_dim_32_decoder_num_hidden_layers_3_decoder_hidden_dim_256','20240226-023459_sc_spectra_latent_dim_32_decoder_num_hidden_layers_3_decoder_hidden_dim_512','20240226-020845_sc_spectra_latent_dim_32_decoder_num_hidden_layers_5_decoder_hidden_dim_128','20240226-022407_sc_spectra_latent_dim_32_decoder_num_hidden_layers_5_decoder_hidden_dim_256','20240226-023939_sc_spectra_latent_dim_32_decoder_num_hidden_layers_5_decoder_hidden_dim_512']]

    # 886,350,431,881,651,381
    # 867,191, 77,736,199,227
    # 1646,409,165,1410,377,106

optimizer:
    optimizer_type: 'adam'

    b1: 0.5
    b2: 0.999
    lr: 1e-4
    spectra_latents_lr: 1e-3
    codebook_pretrain_lr: 1e-3
    weight_decay: 1e-5

    sgd_momentum: 0.9

embedder:
    wave_embed_dim: 16

pretrain:
    pretrain_batch_size: 100

    spectra_latent_dim: -1
    redshift_pretrain_num_spectra: 3200

    negative_supervise_wrong_redshift: False

    load_pretrained_spectra_latents: False
    load_pretrained_spectra_latents_to_gt_bin_only: False
    optimize_gt_bin_only: False
    dont_optimize_gt_bin: False

    pretrain_log_dir: ''
    pretrained_model_name: 'model-ep50000-bch0.pth'

    regularize_spectra_latents: True
    spectra_latents_regu_beta: 16

decoder:
    decoder_batch_norm: False
    decoder_num_hidden_layers: -1
    decoder_hidden_dim: -1
    decoder_skip_layers: [] #[0,1,2,3]

    decoder_activate_before_latents_skip: False
    decoder_latents_skip_all_layers: False
    decoder_latents_skip_method: 'concat'
    decoder_latents_skip_add_conversion_method: 'convert_input'

trainer:
    num_epochs: 1000
    batch_size: 5500
    log_cli_every: 100
    plot_grad_every: -1
    save_model_every: 100

    apply_gt_redshift: False                       # |_these options conflict each other
    optimize_spectra_for_each_redshift_bin: True # |
    calculate_binwise_spectra_loss: True         # | these two should True or False together

    resume_train: False
    resume_log_dir: ''
    resume_model_fname: 'model-ep10000-bch0.pth'

infer:
    infer_last_model_only: True

    infer_log_dir: ''
    infer_selected: False
    pretrain_num_infer_upper_bound: 70
    spectra_inferrence_id_fname: '' #'20240214-133751_sc_400_spectra_2k_epochs_131239/redshift/model-0_redshift_outlier_ids.npy'
    infer_outlier_only: True

    plot_spectrum_with_recon: True
    plot_spectrum_under_gt_bin: False
    plot_spectrum_under_optimal_wrong_bin: False

    num_spectrum_per_fig: 35
    num_spectrum_per_row: 7

    sanity_check_plot_same_pca_dim_as_pretrain: True
    pretrain_pca_dim_fname: '' #'20240225-013832_spectra_latent_dim_32_decoder_num_hidden_layers_5_decoder_hidden_dim_512/latents/2-dim/selected_axes.npy'
    spectra_latents_plot_pca_dim: 2

    plot_redshift_precision_recall: False
    plot_redshift_precision_recall_together: True
    use_logits_as_precision_recall_threshes: False
    num_precision_recall_threshes: 10

spectra_data:
    num_supervision_spectra_upper_bound: 3200
