parent: base_narval.yaml

global:
    use_tqdm: False
    exp_name: 'autodecoder-1600-spectra'
    log_fname: '1600-spectra-skip-same-dim-sep-layers'

    tasks: ['codebook_pretrain']
    #tasks: ['codebook_pretrain_infer','plot_spectra_latents_pca'] #'save_redshift','plot_redshift_residual','plot_redshift_logits']
    #tasks: ['redshift_pretrain']
    #tasks: ['redshift_pretrain_infer','save_redshift','recon_spectra'] #'plot_redshift_logits','plot_redshift_residual'] #'plot_spectra_latents_pca'

ablation:
    perform_ablation: True
    ablat_id: 0
    ablat_params: ["decoder_batch_norm"]
    ablat_vals: [[True,False]]
    ablat_num_vals: [2]

    #ablat_hardcode_params: ["pretrain_log_dir"]
    #ablat_hardcode_vals: [["20240220-172817_3_layers_16_dim_1_regu_beta_skip_same_dim_sep_layers","20240220-172817_3_layers_16_dim_4_regu_beta_skip_same_dim_sep_layers","20240220-172819_3_layers_16_dim_2_regu_beta_skip_same_dim_sep_layers","20240220-173442_3_layers_16_dim_8_regu_beta_skip_same_dim_sep_layers"]]

optimizer:
    optimizer_type: 'adam'

    b1: 0.5
    b2: 0.999
    lr: 1e-4
    spectra_latents_lr: 1e-3
    codebook_pretrain_lr: 1e-3
    weight_decay: 1e-5

    sgd_momentum: 0.9

embedder:
    wave_embed_dim: 16

pretrain:
    pretrain_batch_size: 400

    spectra_latent_dim: 16
    redshift_pretrain_num_spectra: 1600

    negative_supervise_wrong_redshift: False

    load_pretrained_spectra_latents: False
    load_pretrained_spectra_latents_to_gt_bin_only: False
    optimize_gt_bin_only: False
    dont_optimize_gt_bin: False

    pretrain_log_dir: ''
    pretrained_model_name: 'model-ep50000-bch0.pth'

    regularize_spectra_latents: True
    spectra_latents_regu_beta: 16

decoder:
    decoder_batch_norm: True
    decoder_num_hidden_layers: 3
    decoder_hidden_dim: 128
    decoder_skip_layers: [] #[0,1,2,3]

    decoder_latents_skip_all_layers: True
    decoder_latents_skip_with_same_dim: True
    decoder_latents_skip_with_same_dim_sep_layers: True

    decoder_activate_before_latents_skip: True # OBSOLETE

trainer:
    num_epochs: 50000
    batch_size: 5500
    log_cli_every: 5000
    plot_grad_every: -1
    save_model_every: 5000

    apply_gt_redshift: True                       # |_these options conflict each other
    optimize_spectra_for_each_redshift_bin: False # |
    calculate_binwise_spectra_loss: False         # | these two should True or False together

    resume_train: False
    resume_log_dir: ''
    resume_model_fname: 'model-ep10000-bch0.pth'

infer:
    infer_last_model_only: True

    # infer_log_dir: ''

    infer_selected: False
    pretrain_num_infer_upper_bound: 70
    spectra_inferrence_id_fname: '' #'20240214-133751_sc_400_spectra_2k_epochs_131239/redshift/model-0_redshift_outlier_ids.npy'
    infer_outlier_only: True

    plot_spectrum_with_recon: True
    plot_spectrum_under_gt_bin: False
    plot_spectrum_under_optimal_wrong_bin: False

    num_spectrum_per_fig: 35
    num_spectrum_per_row: 7

    sanity_check_plot_same_pca_dim_as_pretrain: True
    pretrain_pca_dim_fname: '' #'20240214-131239_adamw_weight_decay_1e-5_regu_beta_16_50k_epochs/latents/2-dim/selected_axes.npy'
    spectra_latents_plot_pca_dim: 2

    plot_redshift_precision_recall: False
    plot_redshift_precision_recall_together: True
    use_logits_as_precision_recall_threshes: False
    num_precision_recall_threshes: 10

spectra_data:
    num_supervision_spectra_upper_bound: 1600
