parent: base_narval.yaml

global:
    use_tqdm: True
    exp_name: 'autodecoder-3200-spectra'
    log_fname: 'sc-3200-spectra-skip-same-dim'

    tasks: ['codebook_pretrain']
    #tasks: ['codebook_pretrain_infer','plot_spectra_latents_pca'] #'save_redshift','plot_redshift_residual','plot_redshift_logits']
    tasks: ['redshift_pretrain']
    #tasks: ['redshift_pretrain_infer','save_redshift','recon_spectra'] #'plot_redshift_logits','plot_redshift_residual'] #'plot_spectra_latents_pca'

ablation:
    perform_ablation: True
    ablat_id: 0
    ablat_params: ["spectra_latent_dim","decoder_num_hidden_layers","decoder_hidden_dim"]
    ablat_vals: [[8,16,32],[3,5],[128,256,512]]
    ablat_num_vals: [3,2,3]

    ablat_hardcode_params: ["pretrain_log_dir"]
    ablat_hardcode_vals: [['20240223-010632_3200-spectra-skip-same-dim_spectra_latent_dim_8_decoder_num_hidden_layers_3_decoder_hidden_dim_128','20240223-010632_3200-spectra-skip-same-dim_spectra_latent_dim_8_decoder_num_hidden_layers_3_decoder_hidden_dim_256','20240223-010632_3200-spectra-skip-same-dim_spectra_latent_dim_8_decoder_num_hidden_layers_3_decoder_hidden_dim_512','20240223-010632_3200-spectra-skip-same-dim_spectra_latent_dim_8_decoder_num_hidden_layers_5_decoder_hidden_dim_128','20240223-010632_3200-spectra-skip-same-dim_spectra_latent_dim_8_decoder_num_hidden_layers_5_decoder_hidden_dim_256','20240223-011102_3200-spectra-skip-same-dim_spectra_latent_dim_8_decoder_num_hidden_layers_5_decoder_hidden_dim_512','20240223-011135_3200-spectra-skip-same-dim_spectra_latent_dim_16_decoder_num_hidden_layers_3_decoder_hidden_dim_128','20240223-011400_3200-spectra-skip-same-dim_spectra_latent_dim_16_decoder_num_hidden_layers_3_decoder_hidden_dim_256','20240223-011913_3200-spectra-skip-same-dim_spectra_latent_dim_16_decoder_num_hidden_layers_3_decoder_hidden_dim_512','20240223-011959_3200-spectra-skip-same-dim_spectra_latent_dim_16_decoder_num_hidden_layers_5_decoder_hidden_dim_128','20240223-011959_3200-spectra-skip-same-dim_spectra_latent_dim_16_decoder_num_hidden_layers_5_decoder_hidden_dim_256','20240223-012048_3200-spectra-skip-same-dim_spectra_latent_dim_16_decoder_num_hidden_layers_5_decoder_hidden_dim_512','20240223-012148_3200-spectra-skip-same-dim_spectra_latent_dim_32_decoder_num_hidden_layers_3_decoder_hidden_dim_128','20240223-012337_3200-spectra-skip-same-dim_spectra_latent_dim_32_decoder_num_hidden_layers_3_decoder_hidden_dim_256','20240223-012445_3200-spectra-skip-same-dim_spectra_latent_dim_32_decoder_num_hidden_layers_3_decoder_hidden_dim_512','20240223-012454_3200-spectra-skip-same-dim_spectra_latent_dim_32_decoder_num_hidden_layers_5_decoder_hidden_dim_128','20240223-012454_3200-spectra-skip-same-dim_spectra_latent_dim_32_decoder_num_hidden_layers_5_decoder_hidden_dim_256','20240223-012937_3200-spectra-skip-same-dim_spectra_latent_dim_32_decoder_num_hidden_layers_5_decoder_hidden_dim_512']]

optimizer:
    optimizer_type: 'adam'

    b1: 0.5
    b2: 0.999
    lr: 1e-4
    spectra_latents_lr: 1e-3
    codebook_pretrain_lr: 1e-3
    weight_decay: 1e-5

    sgd_momentum: 0.9

embedder:
    wave_embed_dim: 16

pretrain:
    pretrain_batch_size: 100

    spectra_latent_dim: -1
    redshift_pretrain_num_spectra: 3200

    negative_supervise_wrong_redshift: False

    load_pretrained_spectra_latents: False
    load_pretrained_spectra_latents_to_gt_bin_only: False
    optimize_gt_bin_only: False
    dont_optimize_gt_bin: False

    pretrain_log_dir: ''
    pretrained_model_name: 'model-ep50000-bch0.pth'

    regularize_spectra_latents: True
    spectra_latents_regu_beta: 16

decoder:
    decoder_batch_norm: False
    decoder_num_hidden_layers: -1
    decoder_hidden_dim: -1
    decoder_skip_layers: [] #[0,1,2,3]

    decoder_latents_skip_all_layers: True
    decoder_latents_skip_with_same_dim: True
    decoder_latents_skip_with_same_dim_sep_layers: False

    decoder_activate_before_latents_skip: True # OBSOLETE

trainer:
    num_epochs: 1000
    batch_size: 5500
    log_cli_every: 100
    plot_grad_every: -1
    save_model_every: 100

    apply_gt_redshift: False                       # |_these options conflict each other
    optimize_spectra_for_each_redshift_bin: True # |
    calculate_binwise_spectra_loss: True         # | these two should True or False together

    resume_train: False
    resume_log_dir: ''
    resume_model_fname: 'model-ep10000-bch0.pth'

infer:
    infer_last_model_only: True

    # infer_log_dir: ''

    infer_selected: False
    pretrain_num_infer_upper_bound: 70
    spectra_inferrence_id_fname: '' #'20240214-133751_sc_400_spectra_2k_epochs_131239/redshift/model-0_redshift_outlier_ids.npy'
    infer_outlier_only: True

    plot_spectrum_with_recon: True
    plot_spectrum_under_gt_bin: False
    plot_spectrum_under_optimal_wrong_bin: False

    num_spectrum_per_fig: 35
    num_spectrum_per_row: 7

    sanity_check_plot_same_pca_dim_as_pretrain: True
    pretrain_pca_dim_fname: '' #'20240214-131239_adamw_weight_decay_1e-5_regu_beta_16_50k_epochs/latents/2-dim/selected_axes.npy'
    spectra_latents_plot_pca_dim: 2

    plot_redshift_precision_recall: False
    plot_redshift_precision_recall_together: True
    use_logits_as_precision_recall_threshes: False
    num_precision_recall_threshes: 10

spectra_data:
    num_supervision_spectra_upper_bound: 3200
