parent: base.yaml

global:
    use_tqdm: True
    exp_name: 'autodecoder-1600-spectra-pe'
    log_fname: 'sc'

    tasks: ['sanity_check'] #,'recon_spectra']
    tasks: ['sanity_check_infer','recon_spectra','save_redshift','plot_redshift_est_residuals','plot_redshift_est_stats'] #'plot_est_redshift_logits']'plot_spectra_latents_pca'

optimizer:
    optimizer_type: 'adam'

    b1: 0.5
    b2: 0.999
    lr: 1e-4
    spectra_latents_lr: 1e-3
    codebook_pretrain_lr: 1e-3
    weight_decay: 1e-5

    sgd_momentum: 0.9

embedder:
    encode_wave: True
    wave_encode_method: positional_encoding
    wave_embed_dim: 16

pretrain:
    pretrain_batch_size: 50

    pretrain_use_all_wave: False
    pretrain_num_wave_samples: 50
    pretrain_wave_sample_method: 'uniform_dense'
    
    apply_gt_redshift: False
    calculate_binwise_spectra_loss: True # brute force, each bin has its own spectra

    # if brute force, we have three choices
    regularize_binwise_spectra_latents: False     # conflicts each other
    optimize_latents_for_each_redshift_bin: True  #
    # optimize_one_latent_for_all_redshift_bins:  # hidden, True if the other two False

    calculate_spectra_loss_based_on_optimal_bin: True # only if we use single latent
    calculate_spectra_loss_based_on_top_n_bins: False # only if we use single latent
    num_bins_to_calculate_spectra_loss: 5

    classify_redshift_based_on_l2: False

    spectra_latent_dim: 16

    sample_from_codebook_pretrain_spectra: True
    sanity_check_max_num_spectra: 100

    load_pretrained_spectra_latents: False
    load_pretrained_spectra_latents_to_gt_bin_only: False
    optimize_gt_bin_only: False
    dont_optimize_gt_bin: False

    pretrain_log_dir: '20240422-202457_ssim_32_in_3_512_no_skip_no_regu_4k_epochs_r'
    pretrained_model_name: 'model-ep2000-bch0.pth'

    regularize_spectra_latents: False
    spectra_latents_regu_beta: -1

    regress_lambdawise_weights: True
    regress_lambdawise_weights_share_latents: True
    regress_lambdawise_weights_use_gt_bin_latent: True
    wrong_bin_regu_beta: 1
    lambdawise_weights_decoder_num_layers: 1
    lambdawise_weights_decoder_hidden_dim: 128

decoder:
    decoder_activation_type: relu #gaussian
    decoder_batch_norm: False
    decoder_num_hidden_layers: 3
    decoder_hidden_dim: 512
    decoder_skip_layers: []

    decoder_gaussian_sigma: .1

    decoder_activate_before_latents_skip: False
    decoder_latents_skip_all_layers: False
    decoder_latents_skip_method: 'add'
    decoder_latents_skip_add_conversion_method: 'multi_conversion'

trainer:
    num_epochs: 500
    batch_size: 5500
    log_cli_every: 50
    plot_grad_every: 50
    save_data_every: -1
    save_model_every: 50

    plot_l2_loss: True

    resume_train: False
    resume_log_dir: ''
    resume_model_fname: 'model-ep500-bch0.pth'

    spectra_loss_cho: ssim1d
    spectra_loss_reduction: mean
    spectra_lambdawise_loss_reduction: mean
    spectra_ssim_loss_filter_size: 9
    spectra_ssim_loss_filter_sigma: 5

infer:
    infer_last_model_only: True

    # infer_log_dir: ''

    pretrain_infer_batch_size: 1
    pretrain_infer_use_all_wave: True
    pretrain_infer_num_wave: 200
    pretrain_infer_wave_sample_method: 'uniform_non_random'

    infer_selected: False
    pretrain_num_infer_upper_bound: 100
    spectra_inferrence_id_fname: '' #'/redshift/model-0_redshift_outlier_ids.npy'
    infer_outlier_only: False

    plot_clipped_spectrum: True
    plot_spectrum_with_loss: False
    plot_spectrum_with_ivar: False
    plot_spectrum_with_lines: False
    plot_spectrum_with_recon: False
    plot_spectrum_with_weights: True
    plot_spectrum_color_based_on_loss: False
    plot_spectrum_under_gt_bin: True
    plot_spectrum_under_optimal_wrong_bin: True

    num_spectrum_per_fig: 35
    num_spectrum_per_row: 7

    sanity_check_plot_same_pca_dim_as_pretrain: True
    pretrain_pca_dim_fname: '' #'/latents/2-dim/selected_axes.npy'
    spectra_latents_plot_pca_dim: 2

    log_redshift_est_stats: False
    log_redshift_est_stats_residual_levels: [0.02,0.04,0.08]

spectra_data:
    spectra_cho: v1
    spectra_process_patch_info: False
    spectra_data_sources: [deimos,zcosmos]
    random_permute_source_spectra: True

    convolve_spectra: True
    process_ivar: True
    spectra_smooth_sigma: 15

    num_gt_spectra_upper_bound: 1600
    num_supervision_spectra_upper_bound: 1600

    filter_redshift: False
    filter_redshift_lo: 0.02
    filter_redshift_hi: -1

ablation:
    perform_ablation: False
    ablat_id: 0
    ablat_params: ["decoder_batch_norm"] #["decoder_num_hidden_layers","decoder_hidden_dim"]
    ablat_vals: [[True,False]] #[[3,5],[128,256,512]]
    ablat_num_vals: [2] #[2,3]

    ablat_hardcode_params: ["pretrain_log_dir"]
    ablat_hardcode_vals: [["20240222-015410_1600-spectra-skip-same-dim_decoder_batch_norm_True","20240222-165434_1600-spectra-skip-same-dim_decoder_batch_norm_False"]]

    #"20240222-165402_1600-spectra-skip_decoder_batch_norm_True","20240222-165402_1600-spectra-skip_decoder_batch_norm_False"]]
