parent: base.yaml

global:
    use_tqdm: True
    exp_name: vdz-spectra-ssim-t430s-azure
    log_fname: clsfy_small_bsz

    tasks: [train, redshift_classification_train]
    # tasks: [infer, redshift_classification_sc_infer, save_redshift, plot_redshift_est_residuals, plot_redshift_est_stats]
    # tasks: [infer, redshift_classification_genlz_infer, save_redshift, plot_redshift_est_residuals, plot_redshift_est_stats]
    # tasks: [infer, overlay_redshift_est_stats]

optimizer:
    optimizer_type: adam

    b1: 0.5
    b2: 0.999
    lr: 1e-4
    spectra_latents_lr: 1e-3
    spectra_pretrain_lr: 1e-3
    weight_decay: 1e-5

    sgd_momentum: 0.9

pretrain:
    pretrain_batch_size: 256
    pretrain_use_all_wave: True

    classifier_train_use_bin_sampled_data: True
    sanity_check_num_bins_to_sample: 16
    classifier_train_sample_bins: False
    classifier_train_num_bins_to_sample: 2

    classifier_train_add_baseline_logits: True
    classifier_test_add_baseline_logits: True
    
    model_redshift: True
    brute_force_redshift: False
    optimize_latents_for_each_redshift_bin: True

decoder:
    classifier_decoder_input_dim: 280
    classifier_decoder_batch_norm: True
    classifier_decoder_num_hidden_layers: 5
    classifier_decoder_hidden_dim: 512

    classifier_decoder_activate_before_skip: False
    classifier_decoder_skip_all_layers: True
    classifier_decoder_skip_method: add
    classifier_decoder_skip_add_conversion_method: multi_conversion

    classify_based_on_loss: False
    classify_based_on_concat_spectra: True
    classify_based_on_concat_wave_loss: False
    classify_based_on_concat_wave_spectra: False

trainer:
    num_epochs: 10000
    log_cli_every: 1000
    plot_grad_every: -1
    save_data_every: -1
    save_model_every: 1000

    resume_train: False
    resume_log_dir: ''
    resume_model_fname: 'model-ep800-bch0.pth'

infer:
    infer_last_model_only: True

    infer_log_dir: 20240702-001814_clsfy_small_bsz_sanity_check_num_bins_to_sample_16

    infer_selected: False
    pretrain_num_infer_upper_bound: 100
    infer_outlier_only: False

    pretrain_infer_batch_size: 100

    plot_clipped_spectrum: True
    plot_spectrum_with_loss: False
    plot_spectrum_with_ivar: False
    plot_spectrum_with_lines: False
    plot_spectrum_with_recon: False
    plot_spectrum_with_weights: True
    plot_spectrum_color_based_on_loss: False
    plot_spectrum_under_gt_bin: True
    plot_spectrum_under_optimal_wrong_bin: True

    num_spectrum_per_fig: 35
    num_spectrum_per_row: 7

    log_redshift_est_stats: False
    log_redshift_est_stats_residual_levels: [0.02,0.04,0.08]

    redshift_est_stats_labels: ['baseline', 'our_model (5 bins)+baseline', 'our_model (16 bins)+baseline']
    redshift_est_stats_fnames: [vdz-spectra-azure-baseline/20240612-233100_baseline_bin_class_100k_spectra_bn_20k_epochs_lr_1e-5/test_redshift/model-0_all_residuals_accuracy.npy, vdz-spectra-ssim-t430s-azure/20240627-012320_clsfy_small_bsz_bn_5_layers/test_redshift/addup_baseline/model-0_all_residuals_accuracy.npy, vdz-spectra-ssim-t430s-azure/20240702-001814_clsfy_small_bsz_sanity_check_num_bins_to_sample_16/test_redshift/addup_baseline/model-0_all_residuals_accuracy.npy, ]
    overlay_redshift_est_stats_fname: overlay_redshift_est_stats.png

dataset:
    calculate_wave_range_based_on_trans: False
    calculate_wave_range_based_on_spectra: True
    wave_range_fname: wave_range_spectra_6k_to_8k.npy

spectra_data:
    require_only_basic_spectra: True

    spectra_cho: v1
    spectra_process_patch_info: False
    spectra_data_sources: [deimos,zcosmos,vipers_w1,vipers_w4]
    random_permute_source_spectra: True

    spectra_supervision_wave_lo: 6000
    spectra_supervision_wave_hi: 8000

    min_num_valid_samples: 100
    spectra_upsample_scale: 10
    convolve_spectra: True
    process_ivar: True
    spectra_smooth_sigma: 15

    sample_from_pretrain_spectra: True
    sanity_check_max_num_spectra: 200000
    generalization_max_num_spectra: 5000
    num_gt_spectra_upper_bound: 200000
    num_supervision_spectra_upper_bound: 200000

    filter_redshift: False
    filter_redshift_lo: 0.02
    filter_redshift_hi: -1

    redshift_classification_batched_data_fields: [spectra_redshift]
    load_classification_data_individually: False
    redshift_classification_sc_data_dir: 20240626-002713_sc_sanity_check_num_bins_to_sample_16
    redshift_classification_genlz_data_dir: 20240619-220256_genlz_5k_spectra_500_epochs_033031
    redshift_classification_data_fname_prefix: model-0

    baseline_logits_path: vdz-spectra-azure-baseline/20240612-233100_baseline_bin_class_100k_spectra_bn_20k_epochs_lr_1e-5/
    baseline_logits_fname_suffix: model-0

ablation:
    perform_ablation: False
    ablat_id: 0
    ablat_params: [sanity_check_num_bins_to_sample]
    ablat_vals: [[16,32]]
    ablat_num_vals: [2]

    ablat_hardcode_params: [redshift_classification_sc_data_dir]
    ablat_hardcode_vals: [[20240626-002713_sc_sanity_check_num_bins_to_sample_16,20240626-002713_sc_sanity_check_num_bins_to_sample_32]]