parent: base.yaml

global:
    use_tqdm: True
    exp_name: 'dz-spectra-ssim'
    log_fname: 'clsfy' 

    tasks: [train,redshift_classification_train]
    #tasks: [infer,redshift_classification_sc_infer,save_redshift,plot_redshift_est_residuals,plot_redshift_est_stats] #plot_est_redshift_logits]
    #tasks: [infer,redshift_classification_genlz_infer,save_redshift,plot_redshift_est_residuals,plot_redshift_est_stats] #plot_est_redshift_logits]

optimizer:
    optimizer_type: 'adam'

    b1: 0.5
    b2: 0.999
    lr: 1e-4
    spectra_latents_lr: 1e-3
    spectra_pretrain_lr: 1e-3
    weight_decay: 1e-5

    sgd_momentum: 0.9

pretrain:
    pretrain_batch_size: 25

    model_redshift: True
    brute_force_redshift: True
    optimize_latents_for_each_redshift_bin: True

decoder:
    classifier_decoder_input_dim: 280
    classifier_decoder_batch_norm: False
    classifier_decoder_num_hidden_layers: 5
    classifier_decoder_hidden_dim: 512

    classify_based_on_loss: False
    classify_concat_spectra: False
    classify_based_on_wave_loss: True

trainer:
    num_epochs: 200
    log_cli_every: 20
    plot_grad_every: -1
    save_data_every: -1
    save_model_every: 20

    resume_train: False
    resume_log_dir: ''
    resume_model_fname: model-ep1000-bch0.pth

infer:
    infer_last_model_only: True

    infer_log_dir: 20240605-133800_clsfy_1k_spectra_1k_epochs_loss_based_044957

    infer_selected: False
    pretrain_num_infer_upper_bound: 100
    infer_outlier_only: False

    pretrain_infer_batch_size: 25

    plot_clipped_spectrum: True
    plot_spectrum_with_loss: False
    plot_spectrum_with_ivar: False
    plot_spectrum_with_lines: False
    plot_spectrum_with_recon: False
    plot_spectrum_with_weights: True
    plot_spectrum_color_based_on_loss: False
    plot_spectrum_under_gt_bin: True
    plot_spectrum_under_optimal_wrong_bin: True

    num_spectrum_per_fig: 35
    num_spectrum_per_row: 7

    log_redshift_est_stats: False
    log_redshift_est_stats_residual_levels: [0.02,0.04,0.08]

dataset:
    calculate_wave_range_based_on_trans: False
    calculate_wave_range_based_on_spectra: True
    wave_range_fname: wave_range_spectra_5k_to_9k.npy

spectra_data:
    require_only_basic_spectra: True

    redshift_classification_sc_data_dir: 20240605-044957_sc_1k_spectra_200_epochs_cyclecloud
    redshift_classification_genlz_data_dir: 20240605-190502_genlz_1k_spectra_200_epochs_cyclecloud
    redshift_classification_data_fname_prefix: model-0

    spectra_cho: v1
    spectra_process_patch_info: False
    spectra_data_sources: [deimos,zcosmos] #vipers_w1,vipers_w4]
    random_permute_source_spectra: True

    learn_spectra_within_wave_range: True
    wave_range_fname: wave_range_spectra_5k_to_9k.npy
    spectra_supervision_wave_lo: 5000
    spectra_supervision_wave_hi: 9000

    min_num_valid_samples: 100
    spectra_upsample_scale: 10
    convolve_spectra: True
    process_ivar: True
    spectra_smooth_sigma: 15

    sample_from_pretrain_spectra: True
    sanity_check_max_num_spectra: 1000
    generalization_max_num_spectra: 1000
    num_gt_spectra_upper_bound: 25400 #200000
    num_supervision_spectra_upper_bound: 25400 #200000

    filter_redshift: False
    filter_redshift_lo: 0.02
    filter_redshift_hi: -1