parent: base.yaml

global:
    use_tqdm: True
    exp_name: 'autodecoder-3200-spectra-generalize'
    # log_fname: ''

    tasks: ['redshift_pretrain']
    tasks: ['redshift_pretrain_infer','save_redshift','plot_spectra_latents_pca'] #'plot_redshift_logits','plot_redshift_residual'] #

optimizer:
    optimizer_type: 'adam'

    b1: 0.5
    b2: 0.999
    lr: 1e-4
    spectra_latents_lr: 1e-3
    codebook_pretrain_lr: 1e-3
    weight_decay: 1e-5

    sgd_momentum: 0.9

embedder:
    wave_embed_dim: 16

pretrain:
    sample_from_codebook_pretrain_spectra: False
    add_validation_spectra_not_in_supervision: True
    num_extra_validation_spectra: 71 #481 #71

    pretrain_batch_size: 50

    spectra_latent_dim: 32
    redshift_pretrain_num_spectra: 10

    negative_supervise_wrong_redshift: False

    load_pretrained_spectra_latents: False
    load_pretrained_spectra_latents_to_gt_bin_only: False
    optimize_gt_bin_only: False
    dont_optimize_gt_bin: False

    pretrain_log_dir: '20240225-013832_spectra_latent_dim_32_decoder_num_hidden_layers_5_decoder_hidden_dim_512'
    pretrained_model_name: 'model-ep50000-bch0.pth'

    regularize_spectra_latents: True
    spectra_latents_regu_beta: 16

decoder:
    decoder_batch_norm: False
    decoder_num_hidden_layers: 5
    decoder_hidden_dim: 512
    decoder_skip_layers: []

    decoder_activate_before_latents_skip: False
    decoder_latents_skip_all_layers: True
    decoder_latents_skip_method: 'add'
    decoder_latents_skip_add_conversion_method: 'multi_conversion'

trainer:
    num_epochs: 500
    batch_size: 5500
    log_cli_every: 100
    plot_grad_every: -1
    save_model_every: 100

    apply_gt_redshift: False                       # |_these options conflict each other
    optimize_spectra_for_each_redshift_bin: True # |
    calculate_binwise_spectra_loss: True         # | these two should True or False together

    resume_train: False
    resume_log_dir: ''
    resume_model_fname: 'model-ep10000-bch0.pth'

infer:
    infer_last_model_only: True

    infer_log_dir: '20240227-152126_genlz_90_spectra'

    infer_selected: False
    pretrain_num_infer_upper_bound: 140
    spectra_inferrence_id_fname: '' #'/redshift/model-0_redshift_outlier_ids.npy'
    infer_outlier_only: True

    plot_spectrum_with_recon: False
    plot_spectrum_under_gt_bin: True
    plot_spectrum_under_optimal_wrong_bin: True

    num_spectrum_per_fig: 35
    num_spectrum_per_row: 7

    sanity_check_plot_same_pca_dim_as_pretrain: True
    pretrain_pca_dim_fname: '20240225-013832_spectra_latent_dim_32_decoder_num_hidden_layers_5_decoder_hidden_dim_512/latents/2-dim/selected_axes.npy'
    spectra_latents_plot_pca_dim: 2

    plot_redshift_precision_recall: False
    plot_redshift_precision_recall_together: True
    use_logits_as_precision_recall_threshes: False
    num_precision_recall_threshes: 10

spectra_data:
    num_supervision_spectra_upper_bound: 3200

ablation:
    perform_ablation: False
    ablat_id: 0
    ablat_params: ["spectra_latent_dim","decoder_num_hidden_layers","decoder_hidden_dim"]
    ablat_vals: [[8,16,32],[3,5],[128,256,512]]
    ablat_num_vals: [3,2,3]

    #ablat_hardcode_params: []
    #ablat_hardcode_vals: [[]]
