parent: base.yaml

global:
    use_tqdm: True
    exp_name: dz-spectra-ssim-debug
    log_fname: pretrain

    tasks: [train, spectra_pretrain] #, recon_spectra]
    #tasks: [infer, spectra_pretrain_infer, recon_spectra] #'plot_global_lambdawise_spectra_loss'] #'plot_spectra_latents_pca'

optimizer:
    optimizer_type: adam

    b1: 0.5
    b2: 0.999
    lr: 1e-4
    spectra_latents_lr: 1e-3
    spectra_pretrain_lr: 1e-3
    weight_decay: 1e-5

    sgd_momentum: 0.9

embedder:
    encode_wave: True
    wave_encode_method: positional_encoding
    wave_embed_dim: 64
    linear_norm_wave: True
    wave_multiplier: 64

pretrain:
    pretrain_batch_size: 10000

    use_latents_as_coords: True
    zero_init_spectra_latents: True
    optimize_spectra_latents: True
    spectra_latent_dim: 16

    pretrain_use_all_wave: False
    pretrain_num_wave_samples: 100
    pretrain_wave_sample_method: rand_dense

    model_redshift: True
    apply_gt_redshift: True

    regularize_spectra_latents: True
    spectra_latents_regu_beta: 16

decoder:
    decoder_activation_type: relu
    decoder_batch_norm: False
    decoder_num_hidden_layers: 3
    decoder_hidden_dim: 512
    decoder_skip_layers: []

    decoder_gaussian_sigma: .1

    decoder_activate_before_latents_skip: False
    decoder_latents_skip_all_layers: False
    decoder_latents_skip_method: 'add'
    decoder_latents_skip_add_conversion_method: 'multi_conversion'

trainer:
    num_epochs: 2000
    log_cli_every: 200
    plot_grad_every: -1
    save_data_every: -1
    save_model_every: 200

    plot_l2_loss: True

    resume_train: False
    resume_log_dir: ''
    resume_model_fname: model-ep3000-bch0.pth

    spectra_loss_cho: ssim1d
    spectra_loss_reduction: mean
    spectra_ssim_loss_filter_size: 9
    spectra_ssim_loss_filter_sigma: 5

infer:
    infer_last_model_only: True

    # infer_log_dir: 
    infer_selected: True
    pretrain_num_infer_upper_bound: 35
    spectra_inferrence_id_fname: '' #'/redshift/model-0_redshift_outlier_ids.npy'
    infer_outlier_only: False

    pretrain_infer_batch_size: 10
    pretrain_infer_use_all_wave: False
    pretrain_infer_num_wave: 400
    pretrain_infer_wave_sample_method: uniform_dense

    plot_clipped_spectrum: True
    plot_spectrum_with_loss: True
    plot_spectrum_with_ivar: False
    plot_spectrum_with_lines: False
    plot_spectrum_with_recon: True
    plot_spectrum_color_based_on_loss: False
    plot_spectrum_under_gt_bin: False
    plot_spectrum_under_optimal_wrong_bin: False
    plot_global_lambdawise_spectra_loss_with_ivar: False
    plot_global_lambdawise_spectra_loss_with_lines: False
    emitted_wave_overlap_discretization_val: 1e-1

    num_spectrum_per_fig: 35
    num_spectrum_per_row: 7

    spectra_latents_plot_pca_dim: 2

dataset:
    calculate_wave_range_based_on_trans: False
    calculate_wave_range_based_on_spectra: True
    wave_range_fname: wave_range_spectra_6k_to_8k.npy

spectra_data:
    require_only_basic_spectra: True

    spectra_cho: v1
    spectra_process_patch_info: False
    spectra_data_sources: [deimos,zcosmos] #,vipers_w1,vipers_w4]
    random_permute_source_spectra: True

    spectra_supervision_wave_lo: 6000
    spectra_supervision_wave_hi: 8000

    min_num_valid_samples: 100
    spectra_upsample_scale: 10
    convolve_spectra: True
    process_ivar: True
    spectra_smooth_sigma: 15

    num_gt_spectra_upper_bound: 25400
    num_supervision_spectra_upper_bound: 100 #25400

    filter_redshift: False
    filter_redshift_lo: 0.02
    filter_redshift_hi: -1

ablation:
    perform_ablation: False
    ablat_id: 0
    ablat_params: ["spectra_latents_regu_beta","spectra_latent_dim"]
    ablat_vals: [[4,8,16],[16,32,64]]
    ablat_num_vals: [3,3]

    # ablat_hardcode_params: [infer_log_dir]
    # ablat_hardcode_vals: [[30-20240523-231831_pretrain_3_layers_spectra_latents_regu_beta_4_spectra_latent_dim_16,31-20240523-231839_pretrain_3_layers_spectra_latents_regu_beta_4_spectra_latent_dim_32,32-20240523-231832_pretrain_3_layers_spectra_latents_regu_beta_4_spectra_latent_dim_64]]